package main

func main() {
	// variables()
	// constants()
	// for_loop()
	// if_else()
	// switch_golang()
	// arrays()
	// slices_example()
	// maps_golang()
	// vardic_function_golang()
	// closures_golang()
	// recursion_golang()
	// range_over_builtin_types_golang()
	// pointers_golng()
	// string_and_rums()
	// struct_golang()
	// methods_with_struct()
	// interfaces_golang()
	// enum_golang()
	// struct_embeding_golang()
	// generics_golang()
	// range_over_iteration_golang()
	// Errorsgolang()
	// custom_error_golang()
	// coroutine_golang()
	// channels_golang()
	// channel_buffering_golang()
	// channel_sync_golang()
	// channel_directions_golang()
	// channel_select_golang()
	// channel_timeout_golang()
	// channel_non_blocking_golang()
	// channel_closing_golang()
	// channel_range_golang()
	channel_timer_golang()

}
