package main

import (
	"fmt"
	"time"
)

func main() {
	start := time.Now()
	// variables()
	// constants()
	// for_loop()
	// if_else()
	// switch_golang()
	// Arays()
	// Sices_example()
	// Maps_golang()
	// function_call_golang()
	// multiple_return_value_golang()

	// arrays()
	// slices_example()
	// maps_golang()
	// vardic_function_golang()
	// closures_golang()
	// recursion_golang()
	// range_over_builtin_types_golang()
	// pointers_golng()
	// string_and_rums()
	// struct_golang()
	// methods_with_struct()
	// interfaces_golang()
	// enum_golang()
	// struct_embeding_golang()
	// generics_golang()
	// range_over_iteration_golang()
	// Errorsgolang()
	// custom_error_golang()
	// coroutine_golang()
	// channels_golang()
	// channel_buffering_golang()
	// channel_sync_golang()
	// channel_directions_golang()
	// channel_select_golang()
	// channel_timeout_golang()
	// channel_non_blocking_golang()
	// channel_closing_golang()
	// channel_range_golang()
	// channel_timer_golang()
	// channels_tickers_golang()
	// worker_pool_golang()
	// channels_rate_limiting_golang()
	waitgroup_golang()

	elapsed := time.Since(start)
	fmt.Println("total execution time :", elapsed)
}
